field: 32712cfb-8a4d-4f62-ae43-0e6ed9c8714f
fieldLayouts:
  2a337ae0-b7d0-4b4e-9348-9f7c43fb24cd:
    tabs:
      -
        elements:
          -
            fieldUid: 2a68017d-e73c-4bce-9870-876debdde74a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bf154b31-3025-4c4d-932d-94d1969957aa
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 41dc0c40-425c-4459-beda-9c1a12cac627
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2a68017d-e73c-4bce-9870-876debdde74a:
    contentColumnType: text
    fieldGroup: null
    handle: tag
    instructions: ''
    name: Tag
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
  41dc0c40-425c-4459-beda-9c1a12cac627:
    contentColumnType: string
    fieldGroup: null
    handle: column
    instructions: ''
    name: Colonne
    searchable: true
    settings:
      columns:
        __assoc__:
          -
            - 1f45a32b-94ab-47e0-a092-d4bc87f412c6
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 6baa3957-714d-4ca3-a553-9dc75eaf2cf3
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 91f341c6-6785-4efb-9e1e-a369bb49c3e6
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - d4b19b79-cd6e-4287-8892-98d372166baa
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_10_column}}'
      fieldLayout: matrix
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: 'Ajouter une colonne'
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  bf154b31-3025-4c4d-932d-94d1969957aa:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Titre
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
handle: column
name: Colonnes
sortOrder: 4
