field: 32712cfb-8a4d-4f62-ae43-0e6ed9c8714f
fieldLayouts:
  223a8812-e0eb-42db-a0c1-84eb19480324:
    tabs:
      -
        elements:
          -
            fieldUid: b940444d-176f-4180-bdca-bd07ca6fbbdd
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0e1ef1ee-94b0-4b9e-99b9-f7413039cfd0
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 15750c95-7ec5-4eb1-aab2-c091e131c139
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 86eed792-532e-48ea-bff9-b2b4f14be1ae
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0e1ef1ee-94b0-4b9e-99b9-f7413039cfd0:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Titre
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
  15750c95-7ec5-4eb1-aab2-c091e131c139:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Texte
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: language
    type: craft\redactor\Field
  86eed792-532e-48ea-bff9-b2b4f14be1ae:
    contentColumnType: string
    fieldGroup: null
    handle: service
    instructions: ''
    name: Service
    searchable: true
    settings:
      allowSelfRelations: false
      limit: ''
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources:
        - 'section:bea6f06f-12a3-4d09-87c6-94d98009d10e'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  b940444d-176f-4180-bdca-bd07ca6fbbdd:
    contentColumnType: text
    fieldGroup: null
    handle: tag
    instructions: ''
    name: Tag
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
handle: service
name: 'Référence contenu - Services'
sortOrder: 8
