field: 32712cfb-8a4d-4f62-ae43-0e6ed9c8714f
fieldLayouts:
  709b8e02-4abd-412a-b963-f5b14954ccbf:
    tabs:
      -
        elements:
          -
            fieldUid: 5660be1a-d117-4f7a-b667-8b2e0fba12b4
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  5660be1a-d117-4f7a-b667-8b2e0fba12b4:
    contentColumnType: text
    fieldGroup: null
    handle: video
    instructions: ''
    name: Vidéo
    searchable: true
    translationKeyFormat: null
    translationMethod: none
    type: mikestecker\videoembedder\fields\Video
handle: video
name: Vidéo
sortOrder: 6
