fieldLayouts:
  bf171dc3-000e-401e-82b0-dd1a47f65be7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: Titre
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 54e72c54-c984-43fc-b659-5c3982622865
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 08c521cf-a8a6-467e-8ae6-ffcb131478c1 # Titre
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 316f691a-3e46-4649-a09a-50009fdfb13d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a1ce91a5-57d4-4265-947f-535f54610d08 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 79c0e256-a032-40bf-9766-a504e694512c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 97de7b47-515f-4d89-a189-4585140f7564 # Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 477078e3-dc31-4db4-a831-7678c7653b71
            userCondition: null
            warning: null
            width: 100
        name: 'Page header'
        uid: 2e5e6cf7-a23d-42e5-a300-aa4d4d9a032c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 32712cfb-8a4d-4f62-ae43-0e6ed9c8714f # Élément de contenu
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a834d7da-a6ec-487c-90b6-8be1de238959
            userCondition: null
            warning: null
            width: 100
        name: 'Contenu principal'
        uid: 78a31132-64d1-4b8c-9c4a-f8ed92c578ea
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4919cd03-a43a-4d63-856a-0eaf135a26f6 # Call to action
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 55651a93-9359-4f6a-adc0-b3ffa88b3d75
            userCondition: null
            warning: null
            width: 100
        name: 'Call to action'
        uid: 627aec4b-78fd-48b9-a64a-729e45403758
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 12a7f841-74b6-4229-8266-fd7a6d4dd2d8 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0c20911-c5b4-423d-85e4-8057d829d2c6
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: b92827fd-1ee9-4061-815f-80b71a7d22ef
        userCondition: null
handle: blogPost
hasTitleField: false
name: 'Blog post'
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{heading}'
titleTranslationKeyFormat: null
titleTranslationMethod: ''
