fieldLayouts:
  4dee18db-71fe-4f3d-b543-4729370a1c7b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5c3abf14-44ff-44a2-bec3-3688875fe2b6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 08c521cf-a8a6-467e-8ae6-ffcb131478c1 # Titre
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 67a9aace-c328-4c8f-8656-8a3606e90afc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 97de7b47-515f-4d89-a189-4585140f7564 # Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a888ad74-8377-4a85-969e-a3401f3fa435
            userCondition: null
            warning: null
            width: 100
        name: 'Page header'
        uid: 45cd68e6-5a92-4b53-a1e8-15f876847e9d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4919cd03-a43a-4d63-856a-0eaf135a26f6 # Call to action
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72479b34-1ae4-46cc-8371-b9ada956efda
            userCondition: null
            warning: null
            width: 100
        name: 'Call to action'
        uid: 742b3a9e-3beb-447b-88cf-45e579d4bae4
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 12a7f841-74b6-4229-8266-fd7a6d4dd2d8 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d868124f-63fa-4d0d-8607-e9b051b48b0c
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 33bc89e6-68df-49d2-bd9a-84bf6248b37b
        userCondition: null
handle: contact
hasTitleField: false
name: Contact
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{heading}'
titleTranslationKeyFormat: null
titleTranslationMethod: ''
