fieldLayouts:
  2c6fd7ad-b994-4b91-9c9f-9680114de03d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0d761c91-5ad0-49d7-8514-19c7672cdd62
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 08c521cf-a8a6-467e-8ae6-ffcb131478c1 # Titre
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76bca0bd-762d-47d5-adaa-7949def1dac3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 97de7b47-515f-4d89-a189-4585140f7564 # Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5d2690d8-1baf-48fb-b760-be5cc9e1e488
            userCondition: null
            warning: null
            width: 100
        name: 'Page header'
        uid: e604e412-d7fd-4d00-be45-227b5062f715
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4919cd03-a43a-4d63-856a-0eaf135a26f6 # Call to action
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 421d0503-3813-43c6-ba01-9173a815ca15
            userCondition: null
            warning: null
            width: 100
        name: 'Call to action'
        uid: 37106682-7ed0-45b0-865e-04890f1c50fc
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 12a7f841-74b6-4229-8266-fd7a6d4dd2d8 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fdf68b37-8ea8-4b8f-823c-7312f9917631
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 2d43d67b-2eea-4008-a0c6-e3cb6d211a30
        userCondition: null
handle: cookies
hasTitleField: false
name: Cookies
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{heading}'
titleTranslationKeyFormat: null
titleTranslationMethod: ''
