color: null
fieldLayouts:
  6f30f38b-9d84-4491-9d7c-374eb89b6778:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-21T16:03:34+00:00'
            elementCondition: null
            fieldUid: 6c3b9c1c-5126-46d3-8877-1fa714eb9877
            handle: null
            includeInCards: true
            instructions: null
            label: Tag
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98f158a8-c364-49fc-833a-ef24016b1337
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-21T16:03:34+00:00'
            elementCondition: null
            fieldUid: 9fc41b3c-b0a3-444c-8a2e-b14b89a2d856
            handle: heading
            includeInCards: false
            instructions: null
            label: Titre
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db56d032-7b1d-4d42-8ed9-228fec255302
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-21T16:03:34+00:00'
            elementCondition: null
            fieldUid: beb75040-f7a9-475a-bfbd-8cc0b973fccd
            handle: button
            includeInCards: false
            instructions: null
            label: Bouton
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a62dff89-8ce4-4a3e-8363-b86330132a31
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3f5d077a-d373-42c2-9a51-afca8623a0b7
        userCondition: null
handle: cta
hasTitleField: false
icon: null
name: 'Call to action'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
