color: null
fieldLayouts:
  ae36f3ac-0c6d-4e2e-8bc8-32f9dddb3166:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-21T16:03:34+00:00'
            elementCondition: null
            fieldUid: b3b95398-3dc8-4447-a672-84fa7d770d98
            handle: null
            includeInCards: true
            instructions: null
            label: Images
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 54a09cdf-936d-45bf-922d-9a59471d9016
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 573463a3-e93a-47bb-964c-0d259ffcef83
        userCondition: null
handle: gallery
hasTitleField: false
icon: null
name: Galerie
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
