fieldLayouts:
  cd089c40-f1a7-4f79-9b57-0294a5b40930:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 08c521cf-a8a6-467e-8ae6-ffcb131478c1
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 403f5181-c545-4581-8271-e4ca8f45047b
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a1ce91a5-57d4-4265-947f-535f54610d08
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 646a52cb-addd-4be0-873e-12fb37829ca0
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Page Header'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 32712cfb-8a4d-4f62-ae43-0e6ed9c8714f
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Contenu de la page'
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 4919cd03-a43a-4d63-856a-0eaf135a26f6
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Call to action'
        sortOrder: 3
      -
        elements:
          -
            fieldUid: 12a7f841-74b6-4229-8266-fd7a6d4dd2d8
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 4
handle: home
hasTitleField: false
name: Accueil
section: 20358850-5954-4f58-8dc5-0b46ec90da16
sortOrder: 1
titleFormat: '{heading}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
