fieldLayouts:
  e8ca7501-1cd8-43fa-a78f-5d4dd726284a:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 08c521cf-a8a6-467e-8ae6-ffcb131478c1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 97de7b47-515f-4d89-a189-4585140f7564
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Page header'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 4919cd03-a43a-4d63-856a-0eaf135a26f6
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Call to action'
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 12a7f841-74b6-4229-8266-fd7a6d4dd2d8
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 3
handle: partners
hasTitleField: false
name: Partenaires
section: 7082ecb0-2931-42bd-928e-cd9c70a22f5c
sortOrder: 1
titleFormat: '{heading}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
