fieldLayouts:
  e8ca7501-1cd8-43fa-a78f-5d4dd726284a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ac4a4779-d826-486d-94ee-e0fa9b2da004
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 08c521cf-a8a6-467e-8ae6-ffcb131478c1 # Titre
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c87faff6-0c3c-4761-85e4-9308de030b8c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 97de7b47-515f-4d89-a189-4585140f7564 # Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f53b27d6-4c74-4170-99fd-cb2826cf7693
            userCondition: null
            warning: null
            width: 100
        name: 'Page header'
        uid: 3b9217f5-0349-48ca-9d6e-9ea771aa5afc
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4919cd03-a43a-4d63-856a-0eaf135a26f6 # Call to action
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e29275d3-6a4d-4d2c-b1e7-cd9c4d48569f
            userCondition: null
            warning: null
            width: 100
        name: 'Call to action'
        uid: ae8f45c5-1f2f-4d06-9a61-d5f7d308c515
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 12a7f841-74b6-4229-8266-fd7a6d4dd2d8 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e63e7c29-bd7b-47ab-b6ff-6e65e434cb02
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 853354a8-fc16-4a35-b691-70a7a0989a77
        userCondition: null
handle: partners
hasTitleField: false
name: Partenaires
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{heading}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
