fieldLayouts:
  063a5234-58e8-4797-92a2-249542958675:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a409497e-8fb8-4da4-b76d-39e2e65c480d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 08c521cf-a8a6-467e-8ae6-ffcb131478c1 # Titre
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 18b906f6-0b98-427d-aafe-2c464501b384
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 97de7b47-515f-4d89-a189-4585140f7564 # Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 38dab5ac-0adf-4bcc-8737-250102fd4a16
            userCondition: null
            warning: null
            width: 100
        name: 'Page header'
        uid: f25819d7-4a1d-4140-a451-f7dfe189d265
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4919cd03-a43a-4d63-856a-0eaf135a26f6 # Call to action
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72cf5b75-c14d-49a2-8b33-f0e7c0f5c139
            userCondition: null
            warning: null
            width: 100
        name: 'Call to action'
        uid: 19053ff8-75e5-49ee-9b44-fdbd22751c3b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 12a7f841-74b6-4229-8266-fd7a6d4dd2d8 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9b53f1a-7936-40b9-8ed9-a75661817380
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: daba4a05-7e4a-4342-ad05-a03f4a0cb3ee
        userCondition: null
handle: services
hasTitleField: false
name: Services
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: ''
