fieldLayouts:
  063a5234-58e8-4797-92a2-249542958675:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 08c521cf-a8a6-467e-8ae6-ffcb131478c1
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 97de7b47-515f-4d89-a189-4585140f7564
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Page header'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 4919cd03-a43a-4d63-856a-0eaf135a26f6
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Call to action'
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 12a7f841-74b6-4229-8266-fd7a6d4dd2d8
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 3
handle: services
hasTitleField: false
name: Services
section: 35501ad3-f7ed-48c2-b273-8aa2bfbc9bce
sortOrder: 1
titleFormat: '{section.name|raw}'
