fieldLayouts:
  de0a3c4e-85dd-40aa-b032-adca7c4b09bd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: Titre
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bce7dbd7-d850-4d33-b142-16190b64babe
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 08c521cf-a8a6-467e-8ae6-ffcb131478c1 # Titre
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 962d2924-66f9-4ac3-b5af-e08a259b25c1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a1ce91a5-57d4-4265-947f-535f54610d08 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 982c6a0e-38ba-44aa-b264-0c2d702ea40a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 97de7b47-515f-4d89-a189-4585140f7564 # Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2cae87c-122c-46bf-95f5-0d76aa61f36e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 646a52cb-addd-4be0-873e-12fb37829ca0 # Bouton
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8c003cc-e548-49c6-a903-fc73432fe2c3
            userCondition: null
            warning: null
            width: 100
        name: 'Page header'
        uid: de0f97b1-9c00-4204-bbc4-07248a59272c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 32712cfb-8a4d-4f62-ae43-0e6ed9c8714f # Élément de contenu
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f6faec98-0e7a-4846-8c6c-338dd5e3ac6e
            userCondition: null
            warning: null
            width: 100
        name: 'Contenu principal'
        uid: c367d5c3-ebc9-41c0-af99-052a1a7896a2
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4919cd03-a43a-4d63-856a-0eaf135a26f6 # Call to action
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e24ed70-3d8a-4149-b968-00ffdc677849
            userCondition: null
            warning: null
            width: 100
        name: 'Call to action'
        uid: de799c93-eca4-40b2-994b-4ffd5290efeb
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 12a7f841-74b6-4229-8266-fd7a6d4dd2d8 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 85fee64c-930a-4117-864d-37119ab62daf
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 7a06b506-8086-4636-8d5d-4a52f7caf63d
        userCondition: null
handle: service
hasTitleField: false
name: Service
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{heading}'
titleTranslationKeyFormat: null
titleTranslationMethod: ''
