color: null
fieldLayouts:
  3652b9f9-ef05-4315-86bc-db160bd7e8b0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-21T16:03:34+00:00'
            elementCondition: null
            fieldUid: 8bbc4f42-2e96-480d-ba66-f4182e1f59e5
            handle: heading
            includeInCards: true
            instructions: null
            label: Titre
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b1480748-9e60-4d54-be00-7125c8963694
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-21T16:03:34+00:00'
            elementCondition: null
            fieldUid: 8a9b8194-d257-465f-8fbd-f2e63e9ebe42
            handle: text
            includeInCards: false
            instructions: null
            label: Texte
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f86e682-e3a9-4f28-991f-51ebc5250849
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-21T16:03:34+00:00'
            elementCondition: null
            fieldUid: 3a76f952-0f90-4270-a141-d821115a4b11
            handle: button
            includeInCards: false
            instructions: null
            label: Bouton
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ae5fc8d-9987-4c85-be89-50d11c800b20
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-21T16:03:34+00:00'
            elementCondition: null
            fieldUid: 80cf4043-e15d-4dc1-a4d7-d6fd16bbcb9f
            handle: image
            includeInCards: false
            instructions: null
            label: 'Grande image'
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a45d5bcf-9c01-4ab0-9443-1d30996a2c02
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-21T16:03:34+00:00'
            elementCondition: null
            fieldUid: 7703f25a-9c9c-4239-bfc8-a96f4b6d2b00
            handle: null
            includeInCards: false
            instructions: null
            label: 'Petite image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f37d8882-6561-496d-b4d0-51219d1ce072
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 54262eb3-5558-4130-bebe-ddc4e8b2a0fd
        userCondition: null
handle: text2Images
hasTitleField: false
icon: null
name: 'Texte + 2 images'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
