defaultPlacement: end
handle: footerNav1
instructions: null
maxNodes: 6
name: 'Footer nav 1'
propagationMethod: all
siteSettings:
  e3415183-c41b-406f-b496-b97591cc0484: # Institut de Schaltin
    enabled: true
sortOrder: 2
structure:
  maxLevels: 1
  uid: c460b836-c4ba-4ad8-873e-80beb01a02a3
