defaultPlacement: end
handle: footerLegalNav
instructions: null
maxNodes: null
name: 'Footer legal nav'
propagationMethod: all
siteSettings:
  e3415183-c41b-406f-b496-b97591cc0484: # Institut de Schaltin
    enabled: true
sortOrder: 5
structure:
  maxLevels: null
  uid: 1c0ef959-74db-4623-b9c0-b9b3b569636c
