defaultPlacement: end
handle: mainNavigation
instructions: 'Navigation principale du site'
maxNodes: null
name: 'Navigation principale'
propagationMethod: all
siteSettings:
  e3415183-c41b-406f-b496-b97591cc0484: # Institut de Schaltin
    enabled: true
sortOrder: 1
structure:
  maxLevels: null
  uid: 49e0df06-61eb-44a0-a591-e561f0bb75d7
