fieldLayouts:
  72454ad4-86fc-43b2-8479-6e529c06e321:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: c708f287-50a8-433a-8550-24acbb26de80
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 93304c19-bbb1-4d94-ba14-608a857a4244
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Tab 1'
        sortOrder: 1
handle: imageOptimized
hasUrls: true
name: 'Image Optimized'
settings:
  path: '@imagePath'
sortOrder: 3
type: craft\volumes\Local
url: '@imageUrl'
