fieldLayouts:
  72454ad4-86fc-43b2-8479-6e529c06e321:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: f123c90f-b926-4435-b174-faa1b6f393b6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c708f287-50a8-433a-8550-24acbb26de80 # Image Optimized Portrait
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f1133de-a1e2-4ee0-a51d-3b0336a2886a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 93304c19-bbb1-4d94-ba14-608a857a4244 # Image Optimized Landscape
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0117b139-b394-4266-ae6b-c3e147916441
            userCondition: null
            warning: null
            width: 100
        name: 'Tab 1'
        uid: 88d04414-c17d-467b-ab1d-db65aa3cbe2c
        userCondition: null
fs: imageOptimized
handle: imageOptimized
name: 'Image Optimized'
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
