fieldLayouts:
  54012d05-0c9b-4998-8851-04923184eecb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 82edc63f-fa11-433b-9074-ec1b685db867
            userCondition: null
            warning: null
            width: 100
        name: Contenu
        uid: 9b2d4672-c4b6-411a-8797-c40a17b02c24
        userCondition: null
fs: video
handle: video
name: Video
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
