contentColumnType: string
fieldGroup: 2c6828c5-46bf-4ad6-b752-26413ff16eaa
handle: companyGlobalPhone
instructions: ''
name: 'Téléphone principal'
searchable: true
settings:
  country: BE
  customPatternErrorMessage: ''
  customPatternToggle: null
  inputMask: null
  limitToSingleCountry: ''
  mask: null
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: barrelstrength\sproutfields\fields\Phone
