columnSuffix: null
contentColumnType: string
handle: company
instructions: null
name: Société
searchable: true
settings:
  entryTypes:
    - b1a4b74c-4c0c-464c-ae69-6d414ae47399
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
