columnSuffix: null
handle: companyHours
instructions: null
name: 'Société - Société - Heures d''ouverture'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: ''
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: null
  purifyHtml: true
  redactorConfig: null
  removeEmptyTags: true
  removeInlineStyles: true
  removeNbsp: true
  showHtmlButtonForNonAdmins: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: enlarged
translationKeyFormat: null
translationMethod: language
type: craft\redactor\Field
