contentColumnType: string
fieldGroup: 2c6828c5-46bf-4ad6-b752-26413ff16eaa
handle: company
instructions: ''
name: Société
searchable: true
settings:
  contentTable: '{{%matrixcontent_company}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
