columnSuffix: null
contentColumnType: string
handle: cta
instructions: null
name: 'Call to action'
searchable: true
settings:
  entryTypes:
    - 005093b9-ee33-49f7-bea4-a7a2639ee743
  maxEntries: 1
  minEntries: 1
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
