contentColumnType: string
fieldGroup: 3cf03712-85e6-458d-b266-ebbcff427daa
handle: image
instructions: ''
name: Image
searchable: true
settings:
  allowSelfRelations: ''
  allowedKinds: null
  defaultUploadLocationSource: 'volume:ea6d6b66-2a4a-411b-a022-a62793429d7c'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: ''
  selectionLabel: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:1bc7b595-8601-44b4-b427-0e927919a810'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:ea6d6b66-2a4a-411b-a022-a62793429d7c'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: ''
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
