columnSuffix: null
handle: imagePosition
instructions: null
name: 'Élément de contenu - Texte + Image - Image à droite'
searchable: true
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
