contentColumnType: string
fieldGroup: a86a3d97-d25d-43f4-84f4-5c70088453d9
handle: jobAddress
instructions: ''
name: Adresse
searchable: true
settings:
  addressHelper: null
  defaultCountry: BE
  defaultLanguage: fr-BE
  hideCountryDropdown: null
  highlightCountries:
    - BE
  showCountryDropdown: '1'
  value: null
translationKeyFormat: null
translationMethod: language
type: barrelstrength\sproutfields\fields\Address
