columnSuffix: null
contentColumnType: string
handle: seo
instructions: null
name: SEO
searchable: true
settings:
  errorMessage: 'Component class ''ether\seo\fields\SeoField'' belongs to a disabled plugin (SEO).'
  expectedType: ether\seo\fields\SeoField
  settings:
    __assoc__:
      0:
        - description
        - ''
      1:
        - hideSocial
        - ''
      2:
        - robots
        -
          - ''
          - ''
          - ''
          - ''
          - ''
          - ''
      3:
        - socialImage
        - ''
      5:
        - title
        -
          -
            __assoc__:
              -
                - key
                - '1'
              -
                - locked
                - '0'
              -
                - template
                - '{title}'
          -
            __assoc__:
              -
                - key
                - '2'
              -
                - locked
                - '1'
              -
                - template
                - ' - {{ siteName }}'
translationKeyFormat: null
translationMethod: none
type: craft\fields\MissingField
