columnSuffix: null
contentColumnType: string
handle: socialMedia
instructions: null
name: 'Réseaux sociaux'
searchable: true
settings:
  entryTypes:
    - a6307c88-a58e-4dee-bc9b-4edad104442f
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
