columnSuffix: null
handle: text4
instructions: null
name: 'Élément de contenu - Référence contenu - Services - Texte'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: ''
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: null
  purifyHtml: true
  redactorConfig: Simple.json
  removeEmptyTags: true
  removeInlineStyles: true
  removeNbsp: true
  showHtmlButtonForNonAdmins: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
