defaultPlacement: end
enableVersioning: true
entryTypes:
  - 2f60ef7a-837d-4716-912c-7fc5b50d4b71 # Blog post
handle: blogPost
name: 'Blog post'
propagationMethod: all
siteSettings:
  e3415183-c41b-406f-b496-b97591cc0484: # Institut de Schaltin
    enabledByDefault: true
    hasUrls: true
    template: channels/blog-post
    uriFormat: 'actualites/{slug}'
type: channel
