defaultPlacement: end
enableVersioning: true
entryTypes:
  - 2959ce8c-185b-4a61-9766-9db4346fb6b9 # Blog
handle: blog
name: Blog
propagationMethod: all
siteSettings:
  e3415183-c41b-406f-b496-b97591cc0484: # Institut de Schaltin
    enabledByDefault: true
    hasUrls: true
    template: singles/blog
    uriFormat: actualites
type: single
