enableVersioning: true
handle: contact
name: Contact
propagationMethod: all
siteSettings:
  e3415183-c41b-406f-b496-b97591cc0484:
    enabledByDefault: true
    hasUrls: true
    template: singles/contact
    uriFormat: contact
type: single
