enableVersioning: true
handle: devis
name: Devis
propagationMethod: all
siteSettings:
  e3415183-c41b-406f-b496-b97591cc0484:
    enabledByDefault: true
    hasUrls: true
    template: singles/devis
    uriFormat: devis
type: single
