defaultPlacement: end
enableVersioning: true
entryTypes:
  - 98489ce8-64b5-43c5-bbef-4a4f183e120f # Accueil
handle: home
name: Accueil
propagationMethod: all
siteSettings:
  e3415183-c41b-406f-b496-b97591cc0484: # Institut de Schaltin
    enabledByDefault: true
    hasUrls: true
    template: singles/home
    uriFormat: __home__
type: single
