defaultPlacement: end
enableVersioning: true
entryTypes:
  - fe503bc1-01d1-4e05-b46d-a473418e79dd # Landing page
handle: landingPage
name: 'Landing page'
propagationMethod: all
siteSettings:
  e3415183-c41b-406f-b496-b97591cc0484: # Institut de Schaltin
    enabledByDefault: true
    hasUrls: true
    template: structures/landing-page
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: 0410dc47-fee9-42d8-b719-64382529a574
type: structure
