enableVersioning: true
handle: partners
name: Partenaires
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Page entrée primaire'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  e3415183-c41b-406f-b496-b97591cc0484:
    enabledByDefault: true
    hasUrls: true
    template: singles/partners
    uriFormat: partenaire
type: single
