defaultPlacement: end
enableVersioning: true
entryTypes:
  - 480ca47f-2dae-40e7-857f-dc8c7d7a15c8 # Services
handle: services
name: Services
propagationMethod: all
siteSettings:
  e3415183-c41b-406f-b496-b97591cc0484: # Institut de Schaltin
    enabledByDefault: true
    hasUrls: true
    template: singles/services
    uriFormat: service
type: single
