enableVersioning: true
handle: services
name: Services
propagationMethod: all
siteSettings:
  e3415183-c41b-406f-b496-b97591cc0484:
    enabledByDefault: true
    hasUrls: true
    template: singles/services
    uriFormat: service
type: single
